### PR TITLE
Gallery: Streamlines of flow through digital rock

### PR DESCRIPTION
**Pull request by mlesueur**
@lindsayad @fdkong 
Added new gallery gif of streamlines of flow through digital rock, computed with MOOSE Navier-Stokes module

### CODE REVIEW

**Comment by WilkAndy** [comment]
This looks cool, where is it documented, @mlesueur ?

**Comment by mlesueur** [comment]
Thanks @WilkAndy, I think I will have to do another pull request in MOOSE to add the media and its caption in MOOSE gallery
(Flow streamlines computed with the Navier-Stokes module, through a digital rock reconstructed with the Image Reader from a stack of microCT scans).

**Comment by fdkong** [comment]
It looks good to me. @lindsayad Do you have any comments. The video looks very cool

**Comment by lindsayad** [comment]
Very cool!

**Comment by mlesueur** [comment]
Thank you! :)

**Pull request merged**
